apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
  labels:
    app: mlflow
    component: ml-platform
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: 1.6.2
    helm:
      values: |
        replicaCount: 1
        image:
          repository: docker.io/burakince/mlflow
          pullPolicy: IfNotPresent
          tag: "2.17.0"  # Compatible with chart version 1.6.2
        service:
          enabled: true
          type: ClusterIP
          port: 5000
          name: http
          containerPort: 5000
          containerPortName: mlflow
          annotations: {}
        log:
          enabled: true
          level: info
        telemetry:
          enabled: false
        backendStore:
          databaseMigration: true
          databaseConnectionCheck: true
          postgres:
            enabled: true
            host: mlflow-postgres-postgresql.mlflow.svc.cluster.local
            port: 5432
            database: mlflow
            user: mlflow
            password: mlflowpass
            driver: psycopg2
          
        artifactRoot:
          
          s3:
            enabled: true
            bucket: mlflow-artifacts
            accessKey: minio
            secretKey: minio123
            endpointUrl: http://minio.mlflow.svc.cluster.local:9000
        extraEnvFrom:
          - secretRef:
              name: secrets
        
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
  revisionHistoryLimit: 3





