apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow-app
  namespace: infra-tools
  labels:
    app.kubernetes.io/name: mlflow
    app.kubernetes.io/component: ml-platform
    environment: dev
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: 0.7.19  # Version from your Chart.yaml dependency
    helm:
      values: |
        image:
          repository: ghcr.io/community-charts/mlflow
          tag: 2.17.0  # Compatible with chart version 0.7.19
        backendStore:
          database: postgresql
          postgres:
            host: mlflow-postgres.mlflow.svc.cluster.local
            port: 5432
            database: mlflow
            user: mlflow
            password: mlflowpass
        artifactStore:
          defaultArtifactRoot: s3://mlflow-artifacts
          s3:
            endpointUrl: http://minio.mlflow.svc.cluster.local:9000
            bucketName: mlflow-artifacts
            accessKey: minio
            secretKey: minio123
        service:
          type: ClusterIP
          port: 5000
        envFromSecret: mlflow-secrets
  destination:
    server: https://kubernetes.default.svc
    namespace: mlflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true












