apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
spec:
  destination:
    namespace: mlflow
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: mlflow
    targetRevision: 1.1.6  # Latest stable version as of recent sources
    helm:
      valuesObject:
        image:
          registry: docker.io
          repository: bitnami/mlflow
          tag: 2.17.0  # Compatible with chart version
        backendStoreURI: postgresql://mlflow:mlflowpass@mlflow-postgres.mlflow.svc.cluster.local:5432/mlflow
        defaultArtifactRoot: s3://mlflow-artifacts
        extraEnvVars:
          - name: MLFLOW_S3_ENDPOINT_URL
            value: http://minio.mlflow.svc.cluster.local:9000
          - name: AWS_ACCESS_KEY_ID
            value: minio
          - name: AWS_SECRET_ACCESS_KEY
            value: minio123
        service:
          type: ClusterIP
          port: 5000
        existingSecret: mlflow-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


