apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 71.2.0  # Stable version supporting Pushgateway and Grafana
    helm:
      values: |
        prometheus-pushgateway:
          enabled: true
          service:
            type: ClusterIP
            port: 9091
        grafana:
          enabled: true
          service:
            type: ClusterIP
            port: 3000
        prometheus:
          enabled: false
        alertmanager:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true


